import 'package:intl/intl.dart';
import 'package:intl/intl_standalone.dart';

import 'package:l10n/l10n.dart';

// This file will be generated by the framework (l10n)
import 'package:l10n/locale/messages.dart';

void main(List<String> arguments) {

    findSystemLocale().then((final String locale) {
        print("SystemLocale: $locale"); // in my case: de_AT.UTF-8
        translate.locale = Intl.shortLocale(locale);

        //print((l10n("This is a test").message));
        print(translate(l10n("This is a test")));
    });
}