#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Generates the .arb-Files in test/unit/_resources/l10n
# and the .dart-Files in test/unit/_resources
# -----------------------------------------------------------------------------

# Creates .arb-files for Tests
#   -a Folder for generated .ARB-Files
#   -g Folder for generated .dart-Files
#   -i Inore excluded Folders (by default 'test' is excluded!)
#   test/unit/l10n/ - This folder get's scanned
mkl10n -a test/unit/_resources/l10n -g test/unit/_resources -i test/unit/l10n
