// Copyright (c) 2015, <your name>. All rights reserved. Use of this source code
// is governed by a BSD-style license that can be found in the LICENSE file.

/// This is an awesome library. More dartdocs go here.
library cmdline;

import 'dart:io';
import 'dart:math';

import 'package:intl/intl.dart';
import 'package:logging/logging.dart';
import 'package:logging_handlers/logging_handlers_shared.dart';

import 'package:validate/validate.dart';
import "package:yaml/yaml.dart" as yaml;

import 'package:args/args.dart';

import 'package:l10n/l10n.dart';

// This file will be generated by the framework (l10n / 'mkl10n .')
import 'package:l10n_sample_cmdline/locale/messages.dart';

part "cmdline/Application.dart";
part "cmdline/Config.dart";
part "cmdline/Options.dart";
